// Problem 2: Even Fibonacci Numbers
//
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

#include <stdio.h>

const int MAX = 4000000;
int a = 1, b = 2;
int sum = 0;

int main()
{
    while (b <= MAX)
    {
        if (b % 2 == 0)
        {
            sum += b;
        }
        int temp = a + b;
        a = b;
        b = temp;
    }
    printf("%d\n", sum);
    return 0;
}
